"""create deals

Revision ID: bcb9df986115
Revises: 
Create Date: 2026-09-23 16:19:11.515464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb9df986115'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), sa.Identity(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('founder', sa.Text(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('pitch', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('equity', 'loan', 'grant', name='funding_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('equity_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('("type" <> \'equity\') OR (equity_pct IS NOT NULL)', name='ck_deals_equity_pct_required'),
    sa.CheckConstraint('amount >= 1000', name='ck_deals_amount_min'),
    sa.CheckConstraint('char_length(pitch) <= 120', name='ck_deals_pitch_len'),
    sa.PrimaryKeyConstraint('id')
    )
    deals = sa.table(
        'deals',
        sa.column('company', sa.Text),
        sa.column('founder', sa.Text),
        sa.column('sector', sa.Text),
        sa.column('pitch', sa.Text),
        sa.column('type', sa.Enum('equity', 'loan', 'grant', name='funding_type', create_type=False)),
        sa.column('amount', sa.Integer),
        sa.column('equity_pct', sa.Float),
    )
    op.bulk_insert(deals, [
        {
            'company': 'Finova',
            'founder': 'Priya Sharma',
            'sector': 'Fintech',
            'pitch': 'Digital lending for small businesses.',
            'type': 'equity',
            'amount': 5000000,
            'equity_pct': 8.5,
        },
        {
            'company': 'GreenChain',
            'founder': 'Arjun Nair',
            'sector': 'CleanTech',
            'pitch': 'Traceable clean-energy supply chain.',
            'type': 'equity',
            'amount': 12000000,
            'equity_pct': 12.0,
        },
        {
            'company': 'MedAssist',
            'founder': 'Divya Patel',
            'sector': 'HealthTech',
            'pitch': 'Clinical workflow support for clinics.',
            'type': 'grant',
            'amount': 2500000,
            'equity_pct': None,
        },
        {
            'company': 'AgriLink',
            'founder': 'Suresh Reddy',
            'sector': 'AgriTech',
            'pitch': 'Working capital for farmer groups.',
            'type': 'loan',
            'amount': 8000000,
            'equity_pct': None,
        },
        {
            'company': 'EduSpark',
            'founder': 'Neha Joshi',
            'sector': 'EdTech',
            'pitch': 'Assessments and tutoring for students.',
            'type': 'equity',
            'amount': 3000000,
            'equity_pct': 15.0,
        },
        {
            'company': 'LogiFlow',
            'founder': 'Karan Mehta',
            'sector': 'Logistics',
            'pitch': 'Fleet financing for regional freight.',
            'type': 'loan',
            'amount': 15000000,
            'equity_pct': None,
        },
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deals')
    sa.Enum(name='funding_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
